version: "2"
services:

  lit1:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit1:/root/.lit

  lit2:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit2:/root/.lit

  lit3:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit3:/root/.lit

  lit4:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit4:/root/.lit

  lit5:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit5:/root/.lit

  lit6:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit6:/root/.lit

  lit7:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit7:/root/.lit

  lit8:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit8:/root/.lit

  lit9:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit9:/root/.lit

  lit10:
    image: lit
    depends_on: 
      - litbtcregtest
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit10:/root/.lit

  litbtcregtest:
    image: kylemanna/bitcoind
    restart: always
    depends_on: 
      - littracker
    expose: 
      - "18444"
    volumes:
      - ./data/bitcoind:/bitcoin/.bitcoin

  littracker:
    image: littracker
    restart: always
    depends_on: 
      - littrackermongo
    expose:
      - "46580"
    environment:
      - DB_HOST=littrackermongo
    
  littrackermongo:
    image: mongo
    restart: always
